version: "3"
services:
  docker-redis:
    image: redis:6.0
    container_name: docker-redis
    restart: always
    # 明示的に stop がされない限り，終了ステータスに関係なく常に再起動が行われる
    volumes:
      - ./redis/data:/data
      # ローカルの./redis/dataをコンテナ上の/data(Redisのデータ)にマウントする
      - ./redis/log/:/var/log/redis
      # ローカルの./mysql/logをコンテナ上の/var/log/mysql(MySQLのログ)にマウントする
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      # ローカルの./redis/redis.cnf(Redisの設定ファイル)をコンテナ上の/usr/local/etc/redis/redis.confにマウントする
    ports:
      - "127.0.0.1:63790:6379"
      # ローカルの63790ポートとコンテナの6379ポートをマッピングする
      # ただし，ローカルの63790ポートには127.0.0.1からしかアクセスできない
